#pragma once

#include <array>
#include <shared/vocabulary/vocabulary-types.hxx>

namespace vocabulary
{

inline constexpr std::array<PhraseSeed, 521> kENPhrases = {
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "agreed?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "all good?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "alright?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "clear?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "deal?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "does that work?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "eh?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "got it?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "got that?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "huh?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "is that ok?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "makes sense?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "ok"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "ok?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "right?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "sure?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "understand?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "understood?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "yeah?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "you know what i mean?"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "you with me?"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "actually"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "ah"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "anyhow"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "anyway"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "anyways"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "as a matter of fact"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "at the end of the day"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "basically"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "by the way"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "check this out"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "erm"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "first of all"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "hey"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "hmm"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "hold on"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "honestly"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "huh"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "i guess"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "i mean"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "i suppose"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "i tell you"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "in any case"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "in fact"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "kinda"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "let me see"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "let me tell you"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "let me think"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "like"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "listen"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "listen up"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "look"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "look here"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "oh"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "oh right"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "oh yeah"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "ok"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "okay"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "pretty much"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "right"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "so"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "so anyway"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "so basically"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "so then"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "sort of"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "sure"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "the thing is"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "to be honest"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "to tell you the truth"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "uh"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "uhm"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "um"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "wait"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "well"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "well then"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "well you know"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "whatever"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "yeah"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "you know"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "you know what"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "you know what i mean"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "you see"},
  PhraseSeed{.kind = PhraseKind::Filler, .memoryType = MemoryType::Persona, .phrase = "you see what i mean"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how come"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how else"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how far"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how long"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how many"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how much"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how much is"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how often"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "how's"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "hows"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what about"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what day"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what do you"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what else"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what kind"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what kind of"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what time"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what's"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "what's up"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whats"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whats up"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "when"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "when else"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "when's"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whens"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "where"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "where else"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "where's"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "wheres"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "which"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "who"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "who else"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "who's"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whom"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whos"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whose"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "why"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "why's"},
  PhraseSeed{.kind = PhraseKind::Interrogative, .memoryType = MemoryType::Persona, .phrase = "whys"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "can you remind me"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "can you remind me of"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "did you note"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "did you note down"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "did you write down"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "did you write it down"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do i have anything"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do i have anything today"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do i have anything tomorrow"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know how"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know if"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know what"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know when"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know where"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you know who"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you recall"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "do you remember"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how is"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how long"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how much"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how much does it cost"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how much is"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how often"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "how was"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i can't remember"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i cannot remember"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i don't recall"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i don't remember"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i forgot"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i forgot about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i need to know"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i want to know"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i wanted to ask"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i was wondering"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i was wondering about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i would like to know"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i'd like to know"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "i've forgotten"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "is it on the list"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me how"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me of the"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me of what"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me what"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me when"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me where"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "remind me who"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me how"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me how much"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me what"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me what time"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me when"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me where"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "tell me who"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "we talked about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what are we doing"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what are we having"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what date"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what day"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what did we talk about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what did you say"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what did you say about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what did you tell me"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what did you tell me about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what do i have"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what do i have today"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what do i have tomorrow"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what do we have"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what do we have today"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what do we have tomorrow"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what is the name"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what time"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what time do i"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what time do we"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what time is"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what time was"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what were we talking about"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what's my schedule"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what's on"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what's on the list"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what's the name"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "what's the name of"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "whats on"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "whats the name"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "when did we"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "when do we"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "when is"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "when was"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "where are"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "where did i leave"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "where did i put"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "where did we leave"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "where is"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "who is"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "who was"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "you mentioned"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "you said"},
  PhraseSeed{.kind = PhraseKind::RecallMarker, .memoryType = MemoryType::Persona, .phrase = "you told me"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i am afraid of"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i am allergic to"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i am interested in"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i am into"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i am scared of"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i can't stand"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i cannot stand"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i detest"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i dislike"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i don't like"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i don't mind"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i enjoy"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i hate"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i hate to"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i like"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i like to"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i love"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i love to"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i prefer"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "i'm allergic to"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my anniversary is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my appointment is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my aunt"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my best friend"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my bicycle"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my bike"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my bird"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my birthday is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my boss"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my boyfriend"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my brother"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my brother-in-law"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my car"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my cat"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my class"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my classes"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my colleague"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my course"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my cousin"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my coworker"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my dad"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my daughter"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my dog"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my door"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my dream is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my ex"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my ex-husband"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my ex-wife"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my family"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my father-in-law"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my favorite"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my favourite"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my fiance"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my fiancee"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my fish"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my friend"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my game"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my garage"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my girlfriend"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my goal is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my goddaughter"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my godfather"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my godmother"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my godson"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my grandfather"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my grandma"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my grandmother"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my grandpa"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my half-brother"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my half-sister"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my hamster"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my holidays"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my house"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my husband"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my idea is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my job is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my landlady"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my landlord"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my mom"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my mother-in-law"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my motorbike"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my motorcycle"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my neighbor"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my nephew"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my niece"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my parrot"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my partner"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my pet"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my plan is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my practice"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my project is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my rabbit"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my room"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my roommate"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my schedule is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my shift is"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my sister"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my sister-in-law"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my son"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my spouse"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my stepbrother"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my stepdad"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my stepfather"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my stepmom"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my stepmother"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my stepsister"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my tenant"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my training"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my trip"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my truck"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my turn"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my turtle"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my uncle"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my vacation"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my van"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "my wife"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the accountant"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the air conditioner"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the air conditioning"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the alarm"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the alarm clock"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the appointment"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the attic"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the back door"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the backyard"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the balcony"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the basement"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the bathroom"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the bedroom"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the bird"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the blinds"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the boiler"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the breakfast"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the camera"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the cat"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the checkup"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the cleaner"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the concert"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the delivery guy"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the delivery man"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the dentist"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the dinner"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the dishwasher"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the doctor"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the doctor's appointment"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the dog"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the door"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the door camera"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the doorbell"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the driveway"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the electrician"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the entrance"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the fence"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the fire alarm"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the fish"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the fridge"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the front door"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the fuse box"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the garage"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the garage door"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the garden"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the gardener"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the gas"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the greenhouse"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the hairdresser"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the hallway"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the hamster"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the heater"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the heating"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the inspection"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the intercom"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the internet"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the kids"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the kitchen"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the landlord"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the lawn"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the lawyer"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the living room"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the lock"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the locksmith"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the lunch"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the mailbox"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Episodic, .phrase = "the mailman"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Episodic, .phrase = "the meeting"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the microwave"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the modem"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the motion sensor"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the movie"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the nurse"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the oven"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the parrot"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the party"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the patio"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the physiotherapist"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the plug"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the plumber"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the pool"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the porch"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the rabbit"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the refrigerator"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the repair"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the repairman"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the router"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the series"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the shed"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the show"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the smoke detector"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the stairs"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the storage room"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the switch"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Episodic, .phrase = "the technician"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the terrace"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the thermostat"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the turtle"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the vet"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the video doorbell"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the washing machine"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the wedding"},
  PhraseSeed{.kind = PhraseKind::StatementStart, .memoryType = MemoryType::Persona, .phrase = "the wifi"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "bear in mind that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "can you remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "don't forget it"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "don't forget that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "don't let me forget that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "don't lose it"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Instruction, .phrase = "from now on"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "i need you to remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "i want you to remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "i want you to remind me that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "i would like you to remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "i'd like you to remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "keep in mind that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "keep it in mind"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "kindly remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "make a note that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "make me remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "note down that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "note it down"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Episodic, .phrase = "note that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "please remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "remember it"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "remember that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "remember this"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "remember this for me"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "remind me about that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "remind me that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "so i don't forget"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "so i won't forget"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "take note of that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "take note of the fact that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "take note that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "write down that"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "write it down"},
  PhraseSeed{.kind = PhraseKind::Trigger, .memoryType = MemoryType::Persona, .phrase = "you should remember that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "never mind"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "nevermind"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "forget it"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "forget that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "forget what i said"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "forget about it"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "forget about that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "disregard that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "disregard it"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "scratch that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "cancel that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "cancel it"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "ignore that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "ignore what i said"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "it doesn't matter"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "it does not matter"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "doesn't matter"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "never mind that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "don't save that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "do not save that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "don't note that"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "don't write that down"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "nothing, forget it"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "was just kidding"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "just kidding"},
  PhraseSeed{.kind = PhraseKind::Cancellation, .memoryType = MemoryType::Persona, .phrase = "my bad, forget it"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "agreed"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "all good"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "alright"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "clear"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "deal"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "does that work"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "eh"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "got it"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "got that"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "is that ok"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "makes sense"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "understand"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "understood"},
  PhraseSeed{.kind = PhraseKind::Confirmation, .memoryType = MemoryType::Persona, .phrase = "you with me"},
};

inline constexpr std::array<LexiconSeed, 402> kENLexicon = {
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "i", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "i'd", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "i'll", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "i'm", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "i've", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "me", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "mine", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "my", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "myself", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "our", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "ours", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "ourselves", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "us", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::FirstPerson, .surface = "we", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "aunt", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "best friend", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "boss", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "boyfriend", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "brother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "brother-in-law", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "colleague", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "cousin", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "coworker", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "daddy", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "daughter", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "ex", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "ex-husband", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "ex-wife", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "father", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "father-in-law", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "fiance", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "fiancee", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "friend", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "girlfriend", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "goddaughter", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "godfather", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "godmother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "godson", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "granddaughter", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "grandfather", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "grandma", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "grandmother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "grandpa", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "grandson", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "great-grandfather", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "great-grandma", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "great-grandmother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "great-grandpa", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "half-brother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "half-sister", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "husband", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "landlady", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "landlord", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "mom", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "mommy", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "mother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "mother-in-law", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "mum", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "mummy", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "neighbor", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "nephew", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "niece", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "partner", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "roommate", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "sister", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "sister-in-law", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "son", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "spouse", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "stepbrother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "stepdad", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "stepfather", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "stepmom", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "stepmother", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "stepsister", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "tenant", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "twin", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "twins", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "uncle", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Kinship, .surface = "wife", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "arrives at", .canonical = "arrives_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "arrives home at", .canonical = "arrives_home_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "bathes", .canonical = "bathes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "beeps when", .canonical = "beeps_when"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "birthday is on", .canonical = "birthday_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "can't stand", .canonical = "cannot_stand"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "cannot stand", .canonical = "cannot_stand"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "celebrates her birthday on", .canonical = "birthday_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "celebrates his birthday on", .canonical = "birthday_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "charges", .canonical = "charges_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "closes", .canonical = "closes_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "closes at", .canonical = "closes_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes", .canonical = "visits"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes back at", .canonical = "returns_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes every", .canonical = "visits"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes from", .canonical = "comes_from"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes home at", .canonical = "returns_home_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes on", .canonical = "visits"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "comes to visit", .canonical = "visits"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "connects", .canonical = "connects"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "cooks", .canonical = "cooks"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "cooks breakfast", .canonical = "cooks_breakfast"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "cooks dinner", .canonical = "cooks_dinner"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "cycles", .canonical = "cycles"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "dances", .canonical = "dances"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "detests", .canonical = "hates"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "disconnects", .canonical = "disconnects"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "do not like", .canonical = "dislikes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "does not like", .canonical = "dislikes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "does not sleep well", .canonical = "sleeps_poorly"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "does not smoke", .canonical = "does_not_smoke"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "doesn't sleep well", .canonical = "sleeps_poorly"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "doesn't smoke", .canonical = "does_not_smoke"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "drinks", .canonical = "drinks"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "drives", .canonical = "drives"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "eats", .canonical = "eats"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "eats at", .canonical = "eats_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "eats out", .canonical = "eats_out"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "ends work at", .canonical = "ends_work_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "enjoys", .canonical = "loves"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "exercises", .canonical = "exercises"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "falls asleep at", .canonical = "sleeps_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "finishes work at", .canonical = "ends_work_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "gets home at", .canonical = "arrives_home_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "gets to work at", .canonical = "starts_work_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "gets up at", .canonical = "wakes_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes on holiday", .canonical = "goes_on_vacation"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes on vacation", .canonical = "goes_on_vacation"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes shopping", .canonical = "goes_shopping"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes to", .canonical = "goes_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes to bed at", .canonical = "sleeps_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes to sleep at", .canonical = "sleeps_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "goes to the gym", .canonical = "goes_to_gym"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has a birthday on", .canonical = "birthday_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has a nap", .canonical = "naps"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has a shower", .canonical = "showers"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has allergy to", .canonical = "allergic_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has breakfast at", .canonical = "breakfast_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has class", .canonical = "has_class"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has class at", .canonical = "has_class_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has dinner at", .canonical = "dinner_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has got", .canonical = "has"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has lunch at", .canonical = "lunch_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has to", .canonical = "has_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has to come", .canonical = "has_to_come"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has to go", .canonical = "has_to_go"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "has to work", .canonical = "has_to_work"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "hates", .canonical = "hates"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is", .canonical = "is"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is 20 years old", .canonical = "is_age"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is 30 years old", .canonical = "is_age"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is 40 years old", .canonical = "is_age"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is 50 years old", .canonical = "is_age"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is 60 years old", .canonical = "is_age"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is a fan of", .canonical = "loves"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is afraid of", .canonical = "fears"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is afraid to", .canonical = "fears"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is allergic to", .canonical = "allergic_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is at", .canonical = "located_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is bothered by", .canonical = "bothers"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is called", .canonical = "is"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is considering", .canonical = "considering"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is crazy about", .canonical = "loves"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is from", .canonical = "comes_from"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is in", .canonical = "located_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is interested in", .canonical = "interested_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is into", .canonical = "interested_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is kept in", .canonical = "stored_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is looking for", .canonical = "looking_for"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is looking to", .canonical = "looking_for"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is originally from", .canonical = "comes_from"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is painted", .canonical = "painted_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is planning to", .canonical = "plans"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is scared of", .canonical = "fears"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is scared to", .canonical = "fears"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is served", .canonical = "served_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is set to", .canonical = "set_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is stored in", .canonical = "stored_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is thinking about", .canonical = "considering"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is watered", .canonical = "watered_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "is worried about", .canonical = "worries"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "knows", .canonical = "knows"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "learns", .canonical = "learns"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "leaves at", .canonical = "leaves_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "leaves for work at", .canonical = "leaves_work_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "likes", .canonical = "likes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "lives close to", .canonical = "lives_near"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "lives in", .canonical = "lives_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "lives near", .canonical = "lives_near"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "lives on", .canonical = "lives_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "lives with", .canonical = "lives_with"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "locks", .canonical = "closes_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "loves", .canonical = "loves"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "makes breakfast", .canonical = "cooks_breakfast"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "makes dinner", .canonical = "cooks_dinner"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "moved", .canonical = "moved"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "moved from", .canonical = "moved_from"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "moved in", .canonical = "moved_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "moved out", .canonical = "moved_out"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "moved to", .canonical = "moved_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "naps", .canonical = "naps"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "needs", .canonical = "needs"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "opens at", .canonical = "opens_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "opens with", .canonical = "opens_with"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "orders food", .canonical = "orders_food"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "paints", .canonical = "paints"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "picks up mail", .canonical = "picks_up_mail"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "picks up the mail", .canonical = "picks_up_mail"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "plans to", .canonical = "plans"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "plays", .canonical = "plays"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "plays the guitar", .canonical = "plays_guitar"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "plays the piano", .canonical = "plays_piano"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "prefers", .canonical = "prefers"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "reads", .canonical = "reads"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "retired", .canonical = "retired"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "returns at", .canonical = "returns_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "rides a bike", .canonical = "cycles"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "runs", .canonical = "runs"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "shops at", .canonical = "shops_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "showers", .canonical = "showers"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "sings", .canonical = "sings"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "sleeps", .canonical = "sleeps_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "sleeps poorly", .canonical = "sleeps_poorly"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "sleeps well", .canonical = "sleeps_well"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "smokes", .canonical = "smokes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "speaks", .canonical = "speaks"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "speaks english", .canonical = "speaks_english"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "speaks spanish", .canonical = "speaks_spanish"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "starts work at", .canonical = "starts_work_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "stays at", .canonical = "stays_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "stays home", .canonical = "stays_home"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "studies", .canonical = "studies"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "studies at", .canonical = "studies_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "studies in", .canonical = "studies_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "swims", .canonical = "swims"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "takes a nap", .canonical = "naps"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "takes a shower", .canonical = "showers"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "takes classes", .canonical = "takes_classes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "takes lessons", .canonical = "takes_classes"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "takes the bus", .canonical = "takes_the_bus"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "travels to", .canonical = "travels_to"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "turns off", .canonical = "turns_off"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "turns on", .canonical = "activates_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "understands", .canonical = "understands"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "unlocks", .canonical = "unlocks"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "visits", .canonical = "visits"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wakes up at", .canonical = "wakes_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "walks", .canonical = "walks"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wants", .canonical = "wants"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wants to buy", .canonical = "wants_to_buy"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wants to go", .canonical = "wants_to_go"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wants to sell", .canonical = "wants_to_sell"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wants to travel", .canonical = "wants_to_travel"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "wants to visit", .canonical = "wants_to_visit"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "was born in", .canonical = "born_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "was born on", .canonical = "born_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works", .canonical = "works"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works as", .canonical = "works_as"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works at", .canonical = "works_at"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works for", .canonical = "works_for"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works from home", .canonical = "works_from"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works in", .canonical = "works_in"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works on", .canonical = "works_on"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works out", .canonical = "exercises"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "works weekdays", .canonical = "works_weekdays"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "worries about", .canonical = "worries"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "would like", .canonical = "would_like"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "would love", .canonical = "would_like"},
  LexiconSeed{.kind = LexiconKind::Predicate, .surface = "writes", .canonical = "writes"},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "a", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "about", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "after", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "again", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "already", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "also", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "although", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "always", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "an", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "and", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "another", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "any", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "are", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "argus", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "as", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "at", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "away", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "back", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "be", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "because", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "been", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "before", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "being", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "between", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "both", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "but", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "by", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "can", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "could", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "did", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "do", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "does", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "down", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "during", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "each", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "either", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "etc", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "even", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "every", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "except", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "for", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "from", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "had", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "has", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "have", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "he", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "hello", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "her", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "here", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "hers", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "hey", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "him", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "his", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "i", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "if", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "in", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "instead", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "into", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "is", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "it", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "its", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "just", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "may", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "me", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "might", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "mine", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "more", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "most", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "must", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "my", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "neither", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "never", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "no", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "not", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "note", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "now", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "of", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "often", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "on", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "only", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "onto", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "or", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "other", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "our", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "out", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "over", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "quite", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "really", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "remember", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "same", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "she", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "should", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "since", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "so", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "some", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "sometimes", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "still", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "such", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "than", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "that", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "the", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "their", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "theirs", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "them", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "then", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "there", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "these", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "they", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "this", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "those", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "though", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "to", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "today", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "tomorrow", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "too", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "under", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "unless", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "until", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "up", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "us", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "usually", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "very", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "was", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "we", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "were", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "while", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "will", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "with", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "without", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "would", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "yesterday", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "you", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "your", .canonical = ""},
  LexiconSeed{.kind = LexiconKind::Stopword, .surface = "yours", .canonical = ""},
};

} // namespace vocabulary
